name: leanrbot
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^2.3.0
  flutter_flip_view: ^1.0.3
  page_view_indicator: ^2.0.4
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  mvc_pattern: ^6.0.0
  dio: ^3.0.9
  video_player: ^0.10.11+2
  video_player_platform_interface: ^2.0.2
  audioplayers: ^0.15.1
  intro_slider: ^2.3.1
  url_launcher: ^5.4.11
  flutter_typeahead: ^1.8.3
  firebase_auth: ^0.16.1
  rounded_loading_button: ^1.0.9
  flutter_inapp_purchase: ^2.2.0
  modal_bottom_sheet: ^0.2.0
  auto_size_text: ^2.1.0
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  share: ^0.6.4+3
  firebase_admob: any


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/assets_icons_prev.png
    - assets/images/assets_icons_selectlang_listtop.png
    - assets/images/flags/assets_image_flags_catalan.png
    - assets/images/flags/assets_image_flags_danish.png
    - assets/images/flags/assets_image_flags_dutch.png
    - assets/images/flags/assets_image_flags_english.png
    - assets/images/flags/assets_image_flags_esperanto.png
    - assets/images/flags/assets_image_flags_finnish.png
    - assets/images/flags/assets_image_flags_french.png
    - assets/images/flags/assets_image_flags_galician.png
    - assets/images/flags/assets_image_flags_german.png
    - assets/images/flags/assets_image_flags_greek.png
    - assets/images/flags/assets_image_flags_italian.png
    - assets/images/flags/assets_image_flags_norwegian.png
    - assets/images/flags/assets_image_flags_polish.png
    - assets/images/flags/assets_image_flags_portuguese.png
    - assets/images/flags/assets_image_flags_romanian.png
    - assets/images/flags/assets_image_flags_russian.png
    - assets/images/flags/assets_image_flags_scottish.png
    - assets/images/flags/assets_image_flags_slovak.png
    - assets/images/flags/assets_image_flags_spanish.png
    - assets/images/flags/assets_image_flags_swedish.png
    - assets/images/flags/assets_image_flags_valencian.png
    - assets/images/flags/assets_image_flags_welsh.png
    - assets/images/premium.png
    - assets/images/icon.png
    - assets/images/icon/free.png
    - assets/images/icon/digital.png
    - assets/images/icon/learn.png
    - assets/images/icon/book.png
    - assets/images/icon/books.png
    - assets/images/icon/box.png
    - assets/images/icon/email.png
    - assets/images/icon/friend.png
    - assets/images/icon/full.png
    - assets/images/icon/iap.png
    - assets/images/icon/LB.png
    - assets/images/icon/pay.png
    - assets/images/icon/point.png
    - assets/images/icon/tv.png
    - assets/images/icon/world.png
    - assets/images/landingpage_splash.png
    - assets/images/landscape_splash.png
    - assets/images/robot.png
    - assets/images/tool/assets_icons_audio_play.png
    - assets/images/tool/assets_icons_audio_playing.png
    - assets/images/tool/assets_icons_eye.png
    - assets/images/tool/assets_icons_eye_disabled.png
    - assets/images/tool/assets_icons_favorite.png
    - assets/images/tool/assets_icons_favorite_add.png
    - assets/images/tool/assets_icons_favorite_list.png
    - assets/images/tool/assets_icons_lang_setting.png
    - assets/images/tool/assets_icons_play.png
    - assets/images/tool/assets_icons_star.png
    - assets/verbs.sqlite
    - assets/images/intro_landscape.png
    - assets/images/intro_portrait.png
    - assets/images/book1.png
    - assets/images/book2.png
    - assets/guide.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
