import 'dart:io';
import 'package:leanrbot/controller/databasehelper.dart';

class Config {

  static final String and_ip = 'com.learnbot.month';
  static final String ios_ip = 'com.learn.subscription';

  static final List<String> iapIds =[
    'com.iedutainments.german',
    'com.iedutainments.spanish',
    'com.iedutainments.english',
    'com.iedutainments.italian',
    'com.iedutainments.french',
    'com.iedutainments.portuguse',
    'com.iedutainments.russian',
    'com.iedutainments.greek',
    'com.iedutainments.polish',
    'com.iedutainments.norwegan',
    'com.iedutainments.welsh',
    'com.iedutainments.scottish',
    'com.iedutainments.romanian',
    'com.iedutainments.dutch',
    'com.iedutainments.swedish',
    'com.iedutainments.finnish',
    'com.iedutainments.slovak',
    'com.iedutainments.catalan',
    'com.iedutainments.danish',
    'com.iedutainments.galician',
    'com.iedutainments.valencian',
    'com.iedutainments.esperanto',
  ];

  static final List<String> iapAndroid = [
   'com.iedutainmentsa.german',
    'com.iedutainmentsa.spanish',
    'com.iedutainmentsa.english',
    'com.iedutainmentsa.italian',
    'com.iedutainmentsa.french',
    'com.iedutainmentsa.portuguse',
    'com.iedutainmentsa.russian',
    'com.iedutainmentsa.greek',
    'com.iedutainmentsa.polish',
    'com.iedutainmentsa.norwegan',
    'com.iedutainmentsa.welsh',
    'com.iedutainmentsa.scottish',
    'com.iedutainmentsa.romanian',
    'com.iedutainmentsa.dutch',
    'com.iedutainmentsa.swedish',
    'com.iedutainmentsa.finnish',
    'com.iedutainmentsa.slovak',
    'com.iedutainmentsa.catalan',
    'com.iedutainmentsa.danish',
    'com.iedutainmentsa.galician',
    'com.iedutainmentsa.valencian',
    'com.iedutainmentsa.esperanto',
  ];

  static final List<String> flag_images = [
    'assets_image_flags_german.png',
    'assets_image_flags_spanish.png',
    'assets_image_flags_english.png',
    'assets_image_flags_italian.png',
    'assets_image_flags_french.png',
    'assets_image_flags_portuguese.png',
    'assets_image_flags_russian.png',
    'assets_image_flags_greek.png',
    'assets_image_flags_polish.png',
    'assets_image_flags_norwegian.png',
    'assets_image_flags_welsh.png',
    'assets_image_flags_scottish.png',
    'assets_image_flags_romanian.png',
    'assets_image_flags_dutch.png',
    'assets_image_flags_swedish.png',
    'assets_image_flags_finnish.png',
    'assets_image_flags_slovak.png',
    'assets_image_flags_catalan.png',
    'assets_image_flags_danish.png',
    'assets_image_flags_galician.png',
    'assets_image_flags_valencian.png',
    'assets_image_flags_esperanto.png'
  ];
  static final List<String> second_flag_images = [
    'assets_image_flags_german.png',
    'assets_image_flags_spanish.png',
    'assets_image_flags_english.png',
    'assets_image_flags_italian.png',
    'assets_image_flags_french.png',
    'assets_image_flags_portuguese.png',
    'assets_image_flags_greek.png',
    'assets_image_flags_norwegian.png',
    'assets_image_flags_romanian.png',
    'assets_image_flags_swedish.png',
    'assets_image_flags_finnish.png',
    'assets_image_flags_catalan.png',
    'assets_image_flags_danish.png',
    'assets_image_flags_valencian.png',
  ];

  static final List<String> flag_name = [
    'German',
    'Spanish',
    'English',
    'Italian',
    'French',
    'Portuguese',
    'Russian',
    'Greek',
    'Polish',
    'Norwegian',
    'Welsh',
    'Scottish Gaelic',
    'Romanian',
    'Dutch',
    'Swedish',
    'Finnish',
    'Slovak',
    'Catalan',
    'Danish',
    'Galician',
    'Valencian',
    'Esperanto'
  ];
  static final List<String> second_flag_name = [
    'German',
    'Spanish',
    'English',
    'Italian',
    'French',
    'Portuguese',
    'Greek',
    'Norwegian',
    'Romanian',
    'Swedish',
    'Finnish',
    'Catalan',
    'Danish',
    'Valencian',
  ];
  static final List<String> second_flag_code = [
    'DE',
    'ES',
    'EN',
    'IT',
    'FR',
    'PT',
    'GR',
    'NO',
    'RO',
    'SV',
    'FI',
    'CA',
    'DA',
    'VL',
  ];

  static final List<String> flag_code = [
    'DE',
    'ES',
    'EN',
    'IT',
    'FR',
    'PT',
    'RU',
    'GR',
    'PL',
    'NO',
    'CY',
    'GD',
    'RO',
    'NL',
    'SV',
    'FI',
    'SL',
    'CA',
    'DA',
    'GL',
    'VL',
    'EO'
  ];

  static final List<String> free_list = [
    'tosee',
    'tocome',
    'tohave',
    'toknow',
    'toreceive',
    'towait',
    'toput',
    'tobeable',
    'tothink',
    'toaskfor',
    'tohear',
    'toarrive',
    'tocall',
    'toread',
    'toplay',
    'togo',
    'tomake',
    'totalk',
    'tostudy',
    'tobe',
    'towait',
    'towrite',
    'tofind',
    'tostart',
    'toshower',
    'togive',
    'todecide',
    'todrink',
    'todance',
    'tolearn',
    'tolove',
    'togetmarried'
  ];
  static final databasehelper = DatabaseHelper();
}
